name: Github Workshop

on: 
  release:
     types: [published]

jobs:
  Push_To_Docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code from github repo
        uses: actions/checkout@v2
        with:
        ref: ${{github.event.release.name}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v2
      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME}}/randnum:v0.5

      
      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.18.0
        with:
          payload: |
            {
              "text": "Name: ${{ secrets.NOTIFY_NAME }}\nMatriculation: ${{ secrets.NOTIFY_MATRICULATION }}\nEmail: ${{ secrets.NOTIFY_EMAIL }}\nRepo: ${{ github.Repository_Url }}\nImage name:  ${{ secrets.DOCKERHUB_USERNAME }}/randnum:v0.5\nImage url: ${{ secrets.DOCKERHUB_URL }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
