name: Github 2 Dockerhub 2 Slack

on: 
  release:
    types: [published]

jobs:
  Push_To_Docker:
    runs-on: ubuntu-latest
    steps:

     # https://github.com/marketplace/actions/checkout
      - name: Checkout the code from github repo
        uses: actions/checkout@v3

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      # https://github.com/marketplace/actions/docker-login
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # https://github.com/marketplace/actions/build-and-push-docker-images
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: bellanyein/randnum:v0.5

      
      - 
        name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.18.0
        with:
          # For posting a rich message using Block Kit
          payload: |
            {
              "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Name: Nyein Kalayar Kyaw \nMatriculation: A0249488H \nEmail: e0941681@u.nus.edu \nRepo: git://github.com/BellaNyein/randnum.git \nImage name:  bellanyein/randnum:v0.5 \nImage url: https://hub.docker.com/repository/docker/bellanyein/randnum"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
