name: Github 2 Dockerhub 2 Slack

on:
  push:
    # types: [published]
    # tag:
    # - v1.*

jobs:
  build_and_upload:
    runs-on: ubuntu-latest
    steps:

      # -
      #   name: Set up QEMU
      #   uses: docker/setup-qemu-action@v2

      # -
      #   name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2

      # -
      #   name: Login to DockerHub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      # -
      #   name: Build and push
      #   uses: docker/build-push-action@v3
      #   with:
      #     push: true
      #     tags: bellanyein/randnum:v0.5

      # https://github.com/marketplace/actions/slack-webhook
      - 
        name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.18.0
        with:
          # For posting a rich message using Block Kit
          payload: |
            {
              "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Name: Nyein Kalayar Kyaw \nMatriculation: A0249488H \nEmail: e0941681@u.nus.edu \nRepo: https://github.com/BellaNyein/randnum.git \nImage name:  bellanyein/randnum:v0.5 \nImage Url: https://hub.docker.com/r/bellanyein/randnum/tags"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
